E0s: null
cutoff: 5.0
dataset:
  loader_seed: 5678
  n_edge: 32768
  n_graph: 64
  n_node: 4096
  seed: 1234
  train_num: 704
  train_path: training-data/uniFC5_HCONF_for_molecule.xyz
  valid_fraction: 0.03
initialization:
  seed: 0
model:
  alpha: 0.1
  internal_irreps: 96x0e+ 96x0o  + 64x1e +64x1o +64x2e +64x2o
  num_layers: 2
  num_species: 100
  seed: 777
training:
  ema_decay: 0.99
  energy_weight: 10.0
  forces_weight: 70.0
  learning_rate: 0.007
  max_num_intervals: 100
  patience: 3000
  steps_per_interval: 2000
  stress_weight: 0.0
zs: null
